project:
  type: website
  output-dir: _site

website:
  title: "Trent Ollerenshaw"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: cv.qmd
        text: CV
      - href: publications.qmd
        text: Publications
      - href: teaching.qmd
        text: Teaching
      - href: contact.qmd
        text: Contact
  page-footer:
    left: "© {{< year >}} Trent Ollerenshaw"
    right: "Built with Quarto"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-location: right
    code-fold: false
    smooth-scroll: true
execute:
  freeze: auto